# Generated by Django 4.1.5 on 2023-01-31 15:21

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(8, message='verifu length'), django.core.validators.MinLengthValidator(8), users.models.only_int], verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Esprit emails only', regex='[a-zA-Z0-9]+@esprit.tn')]),
        ),
    ]
