# Generated by Django 4.1.5 on 2023-01-31 15:21

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(validators=[events.models.ValidatorDate]),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, null=True, validators=[events.models.titleValidator]),
        ),
    ]
